import { type Metadata } from 'next'
import 'styles/globals.css'

export const metadata: Metadata = {
  title: 'Synoap - Portifolio',
  description: 'Generated by Next.js'
}

function RootLayout ({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
